server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的id，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8086  #匹配提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配提供服务的路由地址
          predicates: #不止下面一个匹配规则，要用其它的规则可百度一下
            - Path=/payment/getPaymentById #断言，路径相匹配的进行路由
        - id: payment_routh1 #路由的id，没有固定规则，但要求唯一，建议配合服务名
#          uri: http://localhost:8086  #匹配提供服务的路由地址
          uri: lb://cloud-payment-service  #匹配提供服务的路由地址
          predicates: #不止下面一个匹配规则，要用其它的规则可百度一下
            - Path=/payment/timeOut #断言，路径相匹配的进行路由

eureka:
  client:
#    表示是否将自己注册进eurekaServer,默认为true
    register-with-eureka: true
#    是否从eurekaServer提取自己的注册信息,默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/
#      集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
#    主机名修改
    instance-id: gateway9527
#    ip名显示
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xj.springcloud.entity

swagger:
  swagger-ui-open: true
