server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
#         github上的git仓库名
          uri: https://github.com/xiaojun0512/cloud-config-server.git
#         搜索目录
          search-paths:
            - cloud-config-server
      #     读取分支
      label: main
#rabbitMq相关配置,15672是web管理界面的端口；5672是mq访问的端口
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
#    表示是否将自己注册进eurekaServer,默认为true
    register-with-eureka: true
#    是否从eurekaServer提取自己的注册信息,默认为true,单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://localhost:7001/eureka/
#      集群
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
#    主机名修改
    instance-id: config-center3344
#    ip名显示
    prefer-ip-address: true

#rabbitMq相关配置,暴露bus刷新配置的端点
management:
  endpoints:  #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'