server:
  port: 8085
spring:
  application:
    name: consul-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mytest?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
#    consul注册中心
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xj.springcloud.entity

swagger:
  swagger-ui-open: true
